-- MySQL Workbench Synchronization
-- Generated: 2016-11-01 10:10
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: j

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `restaurantDB` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `restaurantDB`.`INGREDIENT` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Name_UNIQUE` (`name` ASC))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `restaurantDB`.`DISH` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `Ingredient_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Dish_Ingredient_idx` (`Ingredient_id` ASC),
  CONSTRAINT `fk_Dish_Ingredient`
  FOREIGN KEY (`Ingredient_id`)
  REFERENCES `restaurantDB`.`INGREDIENT` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `restaurantDB`.`MENU` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Dish_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Menu_Dish1_idx` (`Dish_id` ASC),
  CONSTRAINT `fk_Menu_Dish1`
  FOREIGN KEY (`Dish_id`)
  REFERENCES `restaurantDB`.`DISH` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `restaurantDB`.`RESTAURANT` (
  `idRestaurant` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `Rating` VARCHAR(45) NOT NULL,
  `MENU_id` INT(11) NOT NULL,
  `USER_PROFILE_id` INT(11) NOT NULL,
  `USER_PROFILE_USER_id` INT(11) NOT NULL,
  `USER_PROFILE_USER_ROLE_id` INT(11) NOT NULL,
  PRIMARY KEY (`idRestaurant`, `MENU_id`, `USER_PROFILE_id`, `USER_PROFILE_USER_id`, `USER_PROFILE_USER_ROLE_id`),
  INDEX `fk_RESTAURANT_MENU1_idx` (`MENU_id` ASC),
  INDEX `fk_RESTAURANT_USER_PROFILE1_idx` (`USER_PROFILE_id` ASC, `USER_PROFILE_USER_id` ASC, `USER_PROFILE_USER_ROLE_id` ASC),
  CONSTRAINT `fk_RESTAURANT_MENU1`
  FOREIGN KEY (`MENU_id`)
  REFERENCES `restaurantDB`.`MENU` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_RESTAURANT_USER_PROFILE1`
  FOREIGN KEY (`USER_PROFILE_id` , `USER_PROFILE_USER_id` , `USER_PROFILE_USER_ROLE_id`)
  REFERENCES `restaurantDB`.`USER_PROFILE` (`id` , `USER_id` , `USER_ROLE_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `restaurantDB`.`USER` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `password` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8
  COMMENT = '			';

CREATE TABLE IF NOT EXISTS `restaurantDB`.`USER_ROLE` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `restaurantDB`.`USER_PROFILE` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `USER_id` INT(11) NOT NULL,
  `USER_ROLE_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `USER_id`, `USER_ROLE_id`),
  INDEX `fk_USER_PROFILE_USER1_idx` (`USER_id` ASC),
  INDEX `fk_USER_PROFILE_USER_ROLE1_idx` (`USER_ROLE_id` ASC),
  CONSTRAINT `fk_USER_PROFILE_USER1`
  FOREIGN KEY (`USER_id`)
  REFERENCES `restaurantDB`.`USER` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_USER_PROFILE_USER_ROLE1`
  FOREIGN KEY (`USER_ROLE_id`)
  REFERENCES `restaurantDB`.`USER_ROLE` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
